version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers
    steps:
      - checkout
      - run: echo === Build phase ===
  test:
    docker:
      - image: circleci/ruby:2.4.1-node-browsers
    steps:
      - checkout
      - run: echo === Test phase ===
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test