build:
    docker:
      - image: circleci/ruby:2.6.3-node-browsers    steps:
      - image: circleci/ruby:2.6.3-node-browsers    
      steps:
      - checkout

      -run:
        name:build dependencies
        command:bundle install

      - run:
          name: Greeting
          command: echo Hello, world.
          name: build the jekyll site
          command: bundle exec jekyl build

      - run:
        name: Print the Current Time
        command:date
          name: Print the Current Time
         command:date
